// Post List
export const GET_POST_LIST = 'GET_POST_LIST'
export const GET_POST_LIST_IN_PROGRESS = 'GET_POST_LIST_IN_PROGRESS'
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS'
export const GET_POST_LIST_FAILURE = 'GET_POST_LIST_FAILURE'

// Comments Per Post
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS'
export const GET_POST_COMMENTS_IN_PROGRESS = 'GET_POST_COMMENTS_IN_PROGRESS'
export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS'
export const GET_POST_COMMENTS_FAILURE = 'GET_POST_COMMENTS_FAILURE'

// Add New Comment
export const ADD_POST_COMMENT = 'ADD_POST_COMMENT'
export const ADD_POST_COMMENT_IN_PROGRESS = 'ADD_POST_COMMENT_IN_PROGRESS'
export const ADD_POST_COMMENT_SUCCESS = 'ADD_POST_COMMENT_SUCCESS'
export const ADD_POST_COMMENT_FAILURE = 'ADD_POST_COMMENT_FAILURE'